apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
      CREATE DATABASE IF NOT EXISTS taskdb;
      USE taskdb;

      CREATE TABLE IF NOT EXISTS tasks (
                                          id INT AUTO_INCREMENT PRIMARY KEY,
                                          title VARCHAR(255) NOT NULL,
          description TEXT
          );
